# Generated by Django 5.0.2 on 2025-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='统计日期')),
                ('total_users', models.IntegerField(default=0, verbose_name='总用户数')),
                ('new_users', models.IntegerField(default=0, verbose_name='新增用户数')),
                ('active_users', models.IntegerField(default=0, verbose_name='活跃用户数')),
                ('total_videos', models.IntegerField(default=0, verbose_name='总视频数')),
                ('new_videos', models.IntegerField(default=0, verbose_name='新增视频数')),
                ('total_views', models.IntegerField(default=0, verbose_name='总观看次数')),
                ('total_comments', models.IntegerField(default=0, verbose_name='总评论数')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos', models.IntegerField(default=0, verbose_name='发布视频数')),
                ('total_views', models.IntegerField(default=0, verbose_name='获得观看数')),
                ('total_likes', models.IntegerField(default=0, verbose_name='获得点赞数')),
                ('total_comments', models.IntegerField(default=0, verbose_name='获得评论数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '用户统计',
                'verbose_name_plural': '用户统计',
            },
        ),
        migrations.CreateModel(
            name='VideoStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_views', models.IntegerField(default=0, verbose_name='日观看数')),
                ('daily_likes', models.IntegerField(default=0, verbose_name='日点赞数')),
                ('daily_comments', models.IntegerField(default=0, verbose_name='日评论数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '视频统计',
                'verbose_name_plural': '视频统计',
            },
        ),
    ]
